script: make
before_script:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; make setup_osx ; fi
addons:
  apt:
    packages:
    - libusb-dev
language: c
compiler:
        - clang
        - gcc
os:
        - linux
        - osx
